name: 'ci'

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:

  terraform-ci:
    name: 'terraform-ci'
    runs-on: ubuntu-latest
    environment: ci

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform plan -input=false
