name: terraform-ci
description: terraform ci actions

inputs:
  working_directory:
    description: sources directory
    required: true

runs:
  using: "composite"

  steps:
    - run: terraform -chdir=${{ inputs.directory }}/src/ init
      shell: bash
#    - run: terraform fmt -check
#      working-directory: /src
#    - run: terraform plan -input=false
#      working-directory: /src
