name: ci

on:
  push:
    branches: [ "main", "dev", "feature/*" ]
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:

jobs:
  ci:
    name: 'terraform-ci'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: ci department/backend
        uses: "./.github/workflows/ci"
        with:
          working_directory: './department/backend'

#      - name: ci department/infrastructure
#        uses: /templates/ci.yml
#        with:
#          working_directory: ./department/infrastructure
